# Generated by Django 5.2.3 on 2025-06-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default='nothing', max_length=500),
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
