# Generated by Django 5.2.3 on 2025-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_questions_question_delete_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
