# Generated by Django 5.2.3 on 2025-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='average_score',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
