# Generated by Django 5.2.3 on 2025-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_quiz_average_score_quiz_total_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='average_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_attempts',
            field=models.IntegerField(),
        ),
    ]
