# Generated by Django 5.2.3 on 2025-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_alter_quiz_average_score_alter_quiz_total_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total_attempts',
            field=models.FloatField(),
        ),
    ]
