# Generated by Django 5.2.3 on 2025-07-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_alter_quiz_total_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='total_attempts',
        ),
    ]
